let products=[],settings={};const $=s=>document.querySelector(s);
const waNumber=()=>String(settings.whatsappNumber||'').replace(/\D/g,'');
function waUrl(p){return `https://wa.me/${waNumber()}?text=${encodeURIComponent(`Hello, I want to order "${p.name}". Price: ${p.price||'On request'}.`)}`;}
function card(p){const land=p.landForm;return `<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span class="badge">${p.badge}</span>`:''}</div><div class="product-body"><h3>${p.name}</h3><div class="price">${p.price||''}</div><div class="card-actions ${land?'single-action':''}">${land?`<button class="land-action" data-view="${p.id}">${p.submitLabel||'सेवा के लिए आवेदन करें'}</button>`:`<button class="view-btn" data-view="${p.id}">View Details</button><a class="card-order" href="${waUrl(p)}" target="_blank">Order Now</a>`}</div></div></article>`;}
function render(){const q=($('#search').value||'').toLowerCase(),c=$('#category').value;const list=products.filter(p=>p.active!==false&&(!q||`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(q))&&(c==='all'||p.category===c));$('#allGrid').innerHTML=list.filter(p=>!p.landForm).map(card).join('');$('#empty').classList.toggle('hidden',!list.filter(p=>!p.landForm).length);const lands=products.filter(p=>p.active!==false&&p.landForm&&(!q||`${p.name} ${p.description}`.toLowerCase().includes(q)));$('#landGrid').innerHTML=lands.map(card).join('');bindButtons();}
function bindButtons(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.view)));}
function openDetail(id){const p=products.find(x=>x.id===id);if(!p)return;$('#modalImage').src=p.image;$('#modalName').textContent=p.name;$('#modalPrice').textContent=p.price||'';$('#modalCategory').textContent=p.category||'';$('#modalDescription').textContent=p.description||'';$('#modalBadge').textContent=p.badge||'';$('#modalBadge').classList.toggle('hidden',!p.badge);$('#landFormWrap').classList.toggle('hidden',!p.landForm);$('#modalOrder').classList.toggle('hidden',!!p.landForm);$('#modalOrder').onclick=()=>window.open(waUrl(p),'_blank');$('#landSubmit').textContent=p.submitLabel||'WhatsApp पर भेजें';$('#detailModal').classList.remove('hidden');}
$('#landForm').onsubmit=e=>{e.preventDefault();const p=products.find(x=>x.id===Number($('#landForm').dataset.productId));if(!p)return;const fd=new FormData(e.target);const lines=[`*Anmol Online Store - ${p.name}*`,`Service: ${p.name}`,`Price: ${p.price||'On request'}`,``,`Customer Name: ${fd.get('customerName')}`,`Customer Mobile: ${fd.get('customerMobile')}`,``,`रैयत का नाम: ${fd.get('raiyatName')}`,`खाता संख्या: ${fd.get('khataNo')||'-'}`,`खेसरा संख्या: ${fd.get('khesraNo')||'-'}`,`भाग संख्या (पृष्ठ संख्या): ${fd.get('bhagPage')||'-'}`,`मौजा: ${fd.get('mauja')||'-'}`,`हल्का: ${fd.get('halka')||'-'}`,`जिला: ${fd.get('district')||'-'}`,`राज्य: ${fd.get('state')||'-'}`,``,`अन्य जानकारी: ${fd.get('otherInfo')||'-'}`];window.open(`https://wa.me/${waNumber()}?text=${encodeURIComponent(lines.join('\n'))}`,'_blank');};
function init(){Promise.all([fetch('settings.json').then(r=>r.json()),fetch('products.json').then(r=>r.json())]).then(([s,p])=>{settings=s;products=p;document.title=s.storeName;$('#tgLink').href=s.telegramUrl;$('#waChannel').href=s.whatsappChannel;$('#channelLink').href=s.whatsappChannel;$('#floatWa').href=`https://wa.me/${waNumber()}`;[...new Set(products.map(x=>x.category).filter(Boolean))].forEach(c=>$('#category').insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));render();});setTimeout(()=>{if(!localStorage.getItem('anmol_wa_popup_closed'))$('#channelPopup').classList.remove('hidden')},1800);}
$('#search').oninput=render;$('#category').onchange=render;$('#closeModal').onclick=()=>$('#detailModal').classList.add('hidden');$('#detailModal').onclick=e=>{if(e.target.id==='detailModal')$('#detailModal').classList.add('hidden')};$('#closePopup').onclick=()=>{localStorage.setItem('anmol_wa_popup_closed','1');$('#channelPopup').classList.add('hidden')};$('#landGrid').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){$('#landForm').dataset.productId=b.dataset.view;}});init();
